# Generated by Django 6.0.4 on 2026-04-23 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='Dosagem')),
                ('frequency', models.CharField(choices=[('daily', 'Diário'), ('weekly', 'Semanal'), ('when_needed', 'Quando necessário')], default='daily', max_length=20, verbose_name='Frequência')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Horário de lembrete')),
                ('color', models.CharField(default='#E91E8C', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(default='💊', max_length=10, verbose_name='Ícone')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remédio',
                'verbose_name_plural': 'Remédios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/hora')),
                ('taken', models.BooleanField(default=True, verbose_name='Tomado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medications.medication', verbose_name='Remédio')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-taken_at'],
            },
        ),
    ]
